// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgsMywd4KesKs6gpv_9fXMTTWudzU-ZhY',
    appId: '1:1049305134675:web:142a07857f759ef5d1b8a6',
    messagingSenderId: '1049305134675',
    projectId: 'untitled1-5e6ed',
    authDomain: 'untitled1-5e6ed.firebaseapp.com',
    storageBucket: 'untitled1-5e6ed.firebasestorage.app',
    measurementId: 'G-QJZ4ZVX68P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3LTJx3oOfR5fH3VdEKy0_N_Q9PpjHDxY',
    appId: '1:1049305134675:android:3cb39b069d392d5dd1b8a6',
    messagingSenderId: '1049305134675',
    projectId: 'untitled1-5e6ed',
    storageBucket: 'untitled1-5e6ed.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCj2jTWYpM1yHc2EJ-27mJYO_BD_mSXpiU',
    appId: '1:1049305134675:ios:3616276a127f695cd1b8a6',
    messagingSenderId: '1049305134675',
    projectId: 'untitled1-5e6ed',
    storageBucket: 'untitled1-5e6ed.firebasestorage.app',
    iosBundleId: 'com.example.untitled1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCj2jTWYpM1yHc2EJ-27mJYO_BD_mSXpiU',
    appId: '1:1049305134675:ios:3616276a127f695cd1b8a6',
    messagingSenderId: '1049305134675',
    projectId: 'untitled1-5e6ed',
    storageBucket: 'untitled1-5e6ed.firebasestorage.app',
    iosBundleId: 'com.example.untitled1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCgsMywd4KesKs6gpv_9fXMTTWudzU-ZhY',
    appId: '1:1049305134675:web:be88c475de86a133d1b8a6',
    messagingSenderId: '1049305134675',
    projectId: 'untitled1-5e6ed',
    authDomain: 'untitled1-5e6ed.firebaseapp.com',
    storageBucket: 'untitled1-5e6ed.firebasestorage.app',
    measurementId: 'G-ZVEL7KNLWT',
  );
}
